name: envoy
homepage: "https://github.com/kirklink/envoy"
description: 'Lightweight agentic framework for Dart.'
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  anthropic_sdk_dart: ^0.3.1
dev_dependencies:
  test: ^1.25.0
