name: envoy_tools
homepage: "https://github.com/kirklink/envoy"
description: 'Seed tool library for the Envoy agent framework.'
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  envoy:
    path: ../envoy
  endorse:
    path: ../../endorse
  stanza:
    path: ../../stanza/stanza
  html2md: ^1.3.2
  http: ^1.1.0
  path: ^1.9.0
dev_dependencies:
  build_runner: ^2.4.0
  stanza_builder:
    path: ../../stanza/stanza_builder
  test: ^1.25.0
