name: souvenir
version: 0.1.0
publish_to: none
description: Persistent, human-modeled memory system for autonomous agents.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  stanza:
    path: ../../stanza/stanza
  stanza_sqlite:
    path: ../../stanza/stanza_sqlite
  ulid: ^2.0.1
  path: ^1.9.0

dev_dependencies:
  anthropic_sdk_dart: ^0.3.1
  build_runner: ^2.4.0
  stanza_builder:
    path: ../../stanza/stanza_builder
  test: ^1.25.0
